### ISSUE TITLE
UsageError: Line magic function `%rust_deps` not found.

### ISSUE THREAD

**Issue by briantliao** [axil/rust-magic#1]
![image](https://user-images.githubusercontent.com/15722424/65837693-5bdee800-e2af-11e9-8bf9-c8c58e10ba62.png)

**Comment by axil** [comment]
@bCom5 How did you install rust_magic?

**Comment by axil** [comment]
@bCom5 Try `pip install -U rust_magic`
The docs reflected the latest master branch, not the one in the pypi. 
I've pushed it to pypi as v0.3.3 now.

**Comment by briantliao** [comment]
It works! Thank you very much.
